import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.className} ${geistMono.className} antialiased bg-[#0a0a0a] text-[#ededed] selection:bg-lime-500 selection:text-white`}
			>
				<main className="md:w-1/2 md:mx-auto grid place-content-center min-h-svh px-4 py-8">
					{children}
				</main>
			</body>
		</html>
	);
}
