const statesOfNigeria = [
	{ name: "Abia State", value: "Abia State" },
	{ name: "Adamawa State", value: "Adamawa State" },
	{ name: "Akwa Ibom State", value: "Akwa Ibom State" },
	{ name: "Anambra State", value: "Anambra State" },
	{ name: "Bauchi State", value: "Bauchi State" },
	{ name: "Bayelsa State", value: "Bayelsa State" },
	{ name: "Benue State", value: "Benue State" },
	{ name: "Borno State", value: "Borno State" },
	{ name: "Cross River State", value: "Cross River State" },
	{ name: "Delta State", value: "Delta State" },
	{ name: "Ebonyi State", value: "Ebonyi State" },
	{ name: "Edo State", value: "Edo State" },
	{ name: "Ekiti State", value: "Ekiti State" },
	{ name: "Enugu State", value: "Enugu State" },
	{ name: "Gombe State", value: "Gombe State" },
	{ name: "Imo State", value: "Imo State" },
	{ name: "Jigawa State", value: "Jigawa State" },
	{ name: "Kaduna State", value: "Kaduna State" },
	{ name: "Kano State", value: "Kano State" },
	{ name: "Katsina State", value: "Katsina State" },
	{ name: "Kebbi State", value: "Kebbi State" },
	{ name: "Kogi State", value: "Kogi State" },
	{ name: "Kwara State", value: "Kwara State" },
	{ name: "Lagos State", value: "Lagos State" },
	{ name: "Nasarawa State", value: "Nasarawa State" },
	{ name: "Niger State", value: "Niger State" },
	{ name: "Ogun State", value: "Ogun State" },
	{ name: "Ondo State", value: "Ondo State" },
	{ name: "Osun State", value: "Osun State" },
	{ name: "Oyo State", value: "Oyo State" },
	{ name: "Plateau State", value: "Plateau State" },
	{ name: "Rivers State", value: "Rivers State" },
	{ name: "Sokoto State", value: "Sokoto State" },
	{ name: "Taraba State", value: "Taraba State" },
	{ name: "Yobe State", value: "Yobe State" },
	{ name: "Zamfara State", value: "Zamfara State" },
	{ name: "Abuja (FCT)", value: "Abuja (FCT)" },
];

export default statesOfNigeria;
